version: '3.8'

services:
  leffa-model:
    build:
      context: .
      dockerfile: model/Dockerfile
    volumes:
      - ./ckpts:/app/ckpts
      - ./output:/app/output
    env_file:
      - .env
    ports:
      - "9000:9000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    networks:
      - leffa-network

  leffa-frontend:
    image: nginx:alpine
    volumes:
      - ./frontend:/usr/share/nginx/html
      - ./output:/usr/share/nginx/html/output:ro
    ports:
      - "3001:80"
    depends_on:
      - leffa-model
    networks:
      - leffa-network
    restart: unless-stopped

  leffa-tests:
    build:
      context: ./tests
      dockerfile: Dockerfile
    depends_on:
      - leffa-model
      - leffa-frontend
    environment:
      - FRONTEND_URL=http://leffa-frontend
      - WAIT_TIMEOUT=60000
    volumes:
      - ./tests/results:/app/results
    networks:
      - leffa-network
    profiles:
      - testing

networks:
  leffa-network:
    driver: bridge 